# Criação de um DataFrame

Este material visa a documentação/aprendizagem sobre análise exploratória de um conunto de dados.

A criação de um DataFrame começa na manipulação de um *dicionário* , em que as chaves possuem uma lista de elementos de igual tamanho. Assim, as chaves reprentam as colunas e os valores de sua lista representam o valor da linha.

In [ ]:
import pandas as pd

O exemplo utilizado são os 6 cursos de cada campus da UFSM, note que não foi escolhido todos os cursos devido a quantidade maior do campus sede (Santa Maria).

In [ ]:
import pandas as pd

cursos = pd.DataFrame ({
    "Santa": [ "Artes Cênicas", "Ciências Biológicas", "Administração", "Agronegócio","Agronomia", "Zootecnia"],

    "Cachoeira do": ["Arquitetura e Urbanismo", "Ciência de Dados e Inteligência Artificial","Engenharia Agrícola","Engenharia Elétrica","Engenharia Mecânica", "Engenharia de Transportes e Logística"],

    "Frederico": [ "Agronomia", "Direito", "Engenharia Ambiental e Sanitária", "Engenharia Florestal","Jornalismo", "Sistemas de Informação"],

    "Palmeira das": [ "Administração", "Ciências Biológicas", "Ciências Econômicas", "Enfermagem", "Nutrição", "Zootecnia" ]})

In [ ]:
cursos

,Santa,Cachoeira do,Frederico,Palmeira das
0,Artes Cênicas,Arquitetura e Urbanismo,Agronomia,Administração
1,Ciências Biológicas,Ciência de Dados e Inteligência Artificial,Direito,Ciências Biológicas
2,Administração,Engenharia Agrícola,Engenharia Ambiental e Sanitária,Ciências Econômicas
3,Agronegócio,Engenharia Elétrica,Engenharia Florestal,Enfermagem
4,Agronomia,Engenharia Mecânica,Jornalismo,Nutrição
5,Zootecnia,Engenharia de Transportes e Logística,Sistemas de Informação,Zootecnia

## Informações sobre o DataFrame

In [ ]:
cursos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Santa         6 non-null      object
 1   Cachoeira do  6 non-null      object
 2   Frederico     6 non-null      object
 3   Palmeira das  6 non-null      object
dtypes: object(4)
memory usage: 324.0+ bytes

In [ ]:
cursos.columns

Index(['Santa', 'Cachoeira do', 'Frederico', 'Palmeira das'], dtype='object')

In [ ]:
cursos.describe()

                Santa             Cachoeira do  Frederico   Palmeira das
count               6                        6          6              6
unique              6                        6          6              6
top     Artes Cênicas  Arquitetura e Urbanismo  Agronomia  Administração
freq                1                        1          1              1

## Renomear nomes das tabelas

In [ ]:
cursos_renomeado = cursos.rename(columns={
    "Santa" : "Santa Maria",
    "Cachoeira do" : "Cachoeira do Sul",
    "Frederico" : "Frederico Westphalen",
    "Palmeira das" : "Palmeira das Missões" })

In [ ]:
cursos_renomeado

,Santa Maria,Cachoeira do Sul,Frederico Westphalen,Palmeira das Missões
0,Artes Cênicas,Arquitetura e Urbanismo,Agronomia,Administração
1,Ciências Biológicas,Ciência de Dados e Inteligência Artificial,Direito,Ciências Biológicas
2,Administração,Engenharia Agrícola,Engenharia Ambiental e Sanitária,Ciências Econômicas
3,Agronegócio,Engenharia Elétrica,Engenharia Florestal,Enfermagem
4,Agronomia,Engenharia Mecânica,Jornalismo,Nutrição
5,Zootecnia,Engenharia de Transportes e Logística,Sistemas de Informação,Zootecnia

## Acessando uma coluna

In [ ]:
cursos_renomeado['Palmeira das Missões']

0          Administração
1    Ciências Biológicas
2    Ciências Econômicas
3             Enfermagem
4               Nutrição
5              Zootecnia
Name: Palmeira das Missões, dtype: object

## Selecionando o índice [1] do DataFrame

In [ ]:
cursos_renomeado.iloc[1]

Santa Maria                                    Ciências Biológicas
Cachoeira do Sul        Ciência de Dados e Inteligência Artificial
Frederico Westphalen                                       Direito
Palmeira das Missões                           Ciências Biológicas
Name: 1, dtype: object

## Criação de Series

Criação de DataFrame a partir de uma lista de elementos

In [ ]:
pd.Series([80, 6, 7, 6, 11])

0    80
1     6
2     7
3     6
4    11
dtype: int64

Alteraração dos nomes dos índices e o nome da Series:

In [ ]:
pd.Series([80, 6, 7, 11], index = ["Campus Sanata Maria","Campus Cachoeira do Sul","Campus Frederico Westphalen","Campus Palmeira das Missões"], name= "Quantidade de Cursos por Campus da UFSM")

Campus Sanata Maria            80
Campus Cachoeira do Sul         6
Campus Frederico Westphalen     7
Campus Palmeira das Missões    11
Name: Quantidade de Cursos por Campus da UFSM, dtype: int64

# Criando novas colunas

A criação de uma nova coluna é atráves de uma atribuição de Series de valores a uma nova chave no DataFrame.

In [ ]:
cursos_renomeado["Campus"] = "UFSM"

In [ ]:
cursos_renomeado

,Santa Maria,Cachoeira do Sul,Frederico Westphalen,Palmeira das Missões,Campus
0,Artes Cênicas,Arquitetura e Urbanismo,Agronomia,Administração,UFSM
1,Ciências Biológicas,Ciência de Dados e Inteligência Artificial,Direito,Ciências Biológicas,UFSM
2,Administração,Engenharia Agrícola,Engenharia Ambiental e Sanitária,Ciências Econômicas,UFSM
3,Agronegócio,Engenharia Elétrica,Engenharia Florestal,Enfermagem,UFSM
4,Agronomia,Engenharia Mecânica,Jornalismo,Nutrição,UFSM
5,Zootecnia,Engenharia de Transportes e Logística,Sistemas de Informação,Zootecnia,UFSM

Removendo uma coluna

In [ ]:
del cursos_renomeado["Campus"]

In [ ]:
cursos_renomeado

,Santa Maria,Cachoeira do Sul,Frederico Westphalen,Palmeira das Missões
0,Artes Cênicas,Arquitetura e Urbanismo,Agronomia,Administração
1,Ciências Biológicas,Ciência de Dados e Inteligência Artificial,Direito,Ciências Biológicas
2,Administração,Engenharia Agrícola,Engenharia Ambiental e Sanitária,Ciências Econômicas
3,Agronegócio,Engenharia Elétrica,Engenharia Florestal,Enfermagem
4,Agronomia,Engenharia Mecânica,Jornalismo,Nutrição
5,Zootecnia,Engenharia de Transportes e Logística,Sistemas de Informação,Zootecnia

# Acessando índices no DataFrame

In [ ]:
cursos.index

RangeIndex(start=0, stop=6, step=1)

**Exemplo de DataFrame com Índices Textuais (Labels)**

In [ ]:
avaliacao_ensino_aprendizagem = pd.DataFrame ({
    "ruim" : ["12 alunos", "25 alunos", "15 alunos"],
    "bom" : ["20 alunos", "20 alunos", "10 alunos"],
    "excelente" : ["10 alunos", "20 alunos", "39 alunos" ]
}, index = ["Matemática Discreta", "Fundamentos de Cálculo", "Introdução á Programação" ])

In [ ]:
avaliacao_ensino_aprendizagem.head()

                               ruim        bom  excelente
Matemática Discreta       12 alunos  20 alunos  10 alunos
Fundamentos de Cálculo    25 alunos  20 alunos  20 alunos
Introdução á Programação  15 alunos  10 alunos  39 alunos

In [ ]:
cursos_renomeado.to_csv("./sample_data/DataFrame_analise,exploratoria.csv", index=False)

# Formato de uma Series

Extrai informações como quantidade de entradas, bi-dimensional ou uni-dimensional e suas colunas.

In [ ]:
avaliacao_ensino_aprendizagem.shape

(3, 3)

# Seleção Condiconal: Uso do método query

Ela filtra lnhas de um DataFrame baseado em uma query (pergunta).

In [ ]:
avaliacao_ensino_aprendizagem.query("bom == '20 alunos'")

                             ruim        bom  excelente
Matemática Discreta     12 alunos  20 alunos  10 alunos
Fundamentos de Cálculo  25 alunos  20 alunos  20 alunos

# E se quisermos uma array em ordem alfabética de um DataFrame?

escolhemos todos os valores únicos na coluna "Santa Maria", e ordenamos em ordem crescente alfabética.

In [ ]:
sorted(cursos_renomeado["Santa Maria"].unique())

['Administração',
 'Agronegócio',
 'Agronomia',
 'Artes Cênicas',
 'Ciências Biológicas',
 'Zootecnia']